Repository exasol/bucketfs-java, pull requests merged in 2021-04, with the labels that each got.

#16 #14: Added downloadFileAsString method
  .github/workflows/release_droid_prepare_original_checksum.yml
  .github/workflows/release_droid_print_quick_checksum.yml
  .github/workflows/release_droid_release_on_maven_central.yml
  .github/workflows/release_droid_upload_github_release_assets.yml
  .gitignore
  doc/changes/changelog.md
  doc/changes/changes_1.1.0.md
  doc/design.md
  doc/system_requirements.md
  pom.xml
  src/main/java/com/exasol/bucketfs/ReadEnabledBucket.java
  src/main/java/com/exasol/bucketfs/ReadOnlyBucket.java
  src/test/java/com/exasol/bucketfs/ReadEnabledBucketIT.java
  src/test/java/com/exasol/bucketfs/SyncAwareBucketIT.java
Labels: feature

#20 #18: Improved log message in case optional service name is not present.
  doc/changes/changes_1.1.0.md
  src/main/java/com/exasol/bucketfs/ReadEnabledBucket.java
  src/main/java/com/exasol/bucketfs/WriteEnabledBucket.java
  src/test/java/com/exasol/bucketfs/ReadEnabledBucketTest.java
Labels: bug

#21 #19: Distinugish better between error causes
  .travis.yml
  doc/changes/changelog.md
  doc/changes/changes_1.1.0.md
  doc/changes/changes_2.0.0.md
  errorCodeConfig.yml
  pom.xml
  src/main/java/com/exasol/bucketfs/Bucket.java
  src/main/java/com/exasol/bucketfs/BucketFsMonitor.java
  src/main/java/com/exasol/bucketfs/BucketOperation.java
  src/main/java/com/exasol/bucketfs/ReadEnabledBucket.java
  src/main/java/com/exasol/bucketfs/ReadOnlyBucket.java
  src/main/java/com/exasol/bucketfs/SyncAwareBucket.java
  src/main/java/com/exasol/bucketfs/UnsynchronizedBucket.java
  src/main/java/com/exasol/bucketfs/WriteEnabledBucket.java
  src/main/java/com/exasol/config/BucketFsServiceConfiguration.java
  src/test/java/com/exasol/bucketfs/BucketContentSyncIT.java
  src/test/java/com/exasol/bucketfs/BucketOperationTest.java
  src/test/java/com/exasol/bucketfs/LogBasedBucketFsMonitor.java
  src/test/java/com/exasol/bucketfs/ReadEnabledBucketIT.java
  src/test/java/com/exasol/bucketfs/SyncAwareBucketIT.java
Labels: bug

#22 Merge pull request #22 from exasol/bugfix/15-Missing_test_annotation
  doc/changes/changes_2.0.0.md
  errorCodeConfig.yml
  src/main/java/com/exasol/bucketfs/ReadEnabledBucket.java
  src/test/java/com/exasol/bucketfs/ReadEnabledBucketIT.java
Labels: feature

#24 #23: Prepare for release with RD 0.5.0
  doc/changes/changes_2.0.0.md
  release_config.yml
Labels: refactoring, source:exasol

#25 #4: Fixed repeated upload race-condition.
  .travis.yml
  README.md
  dependencies.md
  doc/changes/changelog.md
  doc/changes/changes_2.0.1.md
  pom.xml
  src/main/java/com/exasol/bucketfs/SyncAwareBucket.java
  src/main/java/com/exasol/bucketfs/WriteEnabledBucket.java
  src/test/java/com/exasol/config/BucketFsServiceConfigurationTest.java
Labels: bug
